<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php
$_menu = $this->getHtml('level-top');
$menuStatus = Mage::getStoreConfig('meigee_categoriesenhanced/options/status');
if ($menuStatus == 1) {
	$navAttr = 'class="nav-wide" id="nav-wide"';
}
else {
	$navAttr = 'class="nav" id="nav"';
}
 
?>
<nav class="nav-container">    
    <ul <?php echo $navAttr; ?>>
        <li class="level0 nav-1 first level-top">
            <a class="level-top" href="<?php echo $this->getBaseUrl(); ?>">
                <span><?php echo $this->__("Home Page") ?></span>
            </a>
        </li>
        <li class="level0 nav-2 level-top">
            <a class="level-top" href="<?php echo $this->getBaseUrl()?>about-us">
                <span><?php echo $this->__("About Us") ?></span>
            </a>
        </li>
        <li class="level0 nav-3 level-top">
            <a class="level-top" href="<?php echo $this->getBaseUrl()?>contact-us">
                <span><?php echo $this->__("Contact Us") ?></span>
            </a>
        </li>
	<?php// echo $_menu; ?>
    </ul>
</nav>