<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
	
	$columnsRatio = $this->getColumnsRatio();
	$_addToCart = $this->addToCart();
	$_price = $this->productPrice();
	$_productName = $this->productName();
	$quickview = $this->quickView();
	$moreviews = $this->getMoreviews();
	$wishlist = $this->wishlist();
	$compareproducts = $this->compareProducts();
	$ratingStars = $this->ratingStars();
	$ratingCustomerLink = $this->ratingCustLink();
	$ratingReviewLink = $this->ratingAddReviewLink();
	$randId = $this->getWidgetId();
	
	$meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
	$fancybox = $meigee_blacknwhite_general['fancybox'];
    $helpImg = $this->helper('ThemeOptionsBlacknwhite/images');
	
	$labelsoptions = $meigee_blacknwhite_general['productlabels'];
	$productOnlyXleft = $meigee_blacknwhite_general['productlabels']['labelonlyxleft'];
	$labelsType = $meigee_blacknwhite_general['productlabels']['labelview'];
	
	switch ($columnsRatio) {
		case 1:
			$imgColumn = 'twenty';
			$descriptionColumn = 'eighty';
		break;
		case 2:
			$imgColumn = 'twenty-five';
			$descriptionColumn = 'seventy-five';
		break;
		case 3:
			$imgColumn = 'thirty';
			$descriptionColumn = 'seventy';
		break;
		case 4:
			$imgColumn = 'thirty-five';
			$descriptionColumn = 'sixty-five';
		break;
		case 5:
			$imgColumn = 'forty';
			$descriptionColumn = 'sixty';
		break;
		case 6:
			$imgColumn = 'forty-five';
			$descriptionColumn = 'fifty-five';
		break;
		case 7:
			$imgColumn = 'fifty';
			$descriptionColumn = 'fifty';
		break;
	}
?>
<?php // List Mode ?>
<ol class="products-list<?php echo ' '.$labelsType; ?> meigee-widget" id="products-list">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php $_iterator=0; if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?><?php if($labelsoptions['labelsorder'] == 'sale_new'):?> labels-sale-new<?php endif; ?>">
            <?php // Product Image ?>
            <div class="image-wrapper <?php echo $imgColumn; ?>">
                <div class="product-img-box<?php if($moreviews){echo ' more-views-mode';} ?>">
					<?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getProductLabels($_product, 'new'); ?>
					<?php if($productOnlyXleft and MAGE::helper('ThemeOptionsBlacknwhite')->getProductOnlyXleft($_product)): ?>
						<?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getProductOnlyXleft($_product); ?>
					<?php else: ?>
						<?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getProductLabels($_product, 'sale'); ?>
					<?php endif; ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 800, null); ?><img <?php echo $helpImg->getImgSources($_product, 'small_image', 800, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <?php // Fancybox
                    if ($fancybox['fancybox_status'] && $fancybox['fancybox_home'] == 1): ?>
                        <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('fancybox'); ?></a>
                    <?php endif; // End Fancybox ?>
					<?php if($_product->isSaleable()): ?>
						<?php if($moreviews): ?>
						<div class="ajax-media-button-holder<?php if(!(Mage::getStoreConfig('ajax/general/enabledpro') and $quickview)){echo ' no-quick-view';} ?>">
							<a href='<?php echo $this->getUrl('meigeeactions/moreviews/index',array('product'=>$_product->getId()));?>' class='ajax-media'><span><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('moreviews'); ?><span><?php echo $this->__('More views') ?></span></span></a>
						</div>
						<div class="ajax-media-overlay"><div class="loader"></div></div>
						<?php endif; ?>
						<?php if(Mage::getStoreConfig('ajax/general/enabledpro') and $quickview){ ?>
						<div class="quick-view-holder">
							<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId().$randId; ?>')"><span><span><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('quickview'); ?><span><?php echo $this->__('Quick View') ?></span></span></span></button>
							<a href='<?php $url = $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId())); if(Mage::app()->getStore()->isCurrentlySecure()){echo str_replace('http:', 'https:',  $url);}else{echo $url;} ?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId().$randId; ?>' style='display:none'>Test</a>
						</div>
						<?php } ?>
					<?php else: ?>
						<div class="out-of-stock-label"><?php echo $this->__('Out of stock') ?></div>
					<?php endif; ?>
                </div>
            </div>
            <?php // Product description ?>
            <div class="description-wrapper <?php echo $descriptionColumn; ?>">
				<div class="product-shop<?php if(!$_product->isSaleable()){echo ' out-of-stock';} ?>">
					<?php if($_productName): ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
					<?php endif; ?>
					<?php $storeId = Mage::app()->getStore()->getId();
					$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
					if ($summaryData['rating_summary']):
						if ($ratingCustomerLink || $ratingReviewLink || $ratingStars) : ?>
							<div class="ratings">
								<?php if ($ratingStars) : ?>
									<div class="rating-box">
										<div class="rating" style="width: <?php echo $summaryData['rating_summary']; ?>%"></div> 
									</div>
								<?php endif; ?>
								<p class="rating-links">
									<?php if ($ratingCustomerLink) : ?>
										<a href="<?php echo $_product->getProductUrl() ?>#review-point"><?php echo $this->__('%d Review(s)', $summaryData['reviews_count']) ?></a>
									<?php endif; ?>
									<?php if ($ratingCustomerLink && $ratingReviewLink) : ?>
										<span class="separator">|</span>
									<?php endif; ?>
									<?php if ($ratingReviewLink) : ?>
										<a href="<?php echo $_product->getProductUrl() ?>#review-point"><?php echo $this->__('Add Your Review') ?></a>
									<?php endif; ?>
								</p>
							</div>
						<?php endif; ?>
					<?php endif; ?>
					<?php if(!$_product->isSaleable()): ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif; ?>
					<?php if($_price): ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
					<?php endif; ?>
					<div class="desc std">
						<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
					</div>
					<?php if($_addToCart): ?>
						<?php if($_product->isSaleable()): ?>
							<?php $standardButton = false; if(Mage::getStoreConfig('ajax/general/enabledpro')): ?>
								<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped() || $_product->isConfigurable())): ?>
									<div class="button-holder">
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php $url = $this->getAddToCartUrl($_product); if(Mage::app()->getStore()->isCurrentlySecure()){echo str_replace('http:', 'https:',  $url);}else{echo $url;} ?>','<?php echo $_product->getId().$randId; ?>', '<?php echo addslashes($this->stripTags($_product->getName(), null, true)) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<span id='ajax_loader<?php echo $_product->getId().$randId; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span>
									</div>
								<?php elseif($quickview): ?>
									<div class="button-holder">
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId().$randId; ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									</div>
								<?php else: $standardButton = true; ?>
								<?php endif; ?>
							<?php else: $standardButton = true; ?>
							<?php endif; ?>
							<?php if($standardButton): ?>
								<div class="button-holder"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
							<?php endif; ?>
						<?php else: ?>
							<div class="button-holder"><button type="button" title="<?php echo $this->__('Read More') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Read More') ?></span></span></button></div>
						<?php endif; ?>
					<?php endif; ?>
					<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
					 <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
                            <li><a href="#" onclick='ajaxWishlist("<?php $url = $this->helper('wishlist')->getAddUrl($_product); if(Mage::app()->getStore()->isCurrentlySecure()){echo str_replace('http:', 'https:',  $url);}else{echo str_replace('https:', 'http:',  $url);} ?>","<?php echo $_product->getId().$randId; ?>");return false;' class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('wishlist'); ?><span id='ajax_wishlist_loading<?php echo $_product->getId().$randId; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt='' /></span></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
                            <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php $url = $_compareUrl; if(Mage::app()->getStore()->isCurrentlySecure()){echo str_replace('http:', 'https:',  $url);}else{echo str_replace('https:', 'http:',  $url);} ?>","<?php echo $_product->getId().$randId; ?>");return false;' class="link-compare"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('compare'); ?><span id='ajax_loading<?php echo $_product->getId().$randId; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt='' /></span></a></li>
                        <?php endif; ?>
                    </ul>
					<?php }else{?>
					<ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('wishlist'); ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsBlacknwhite')->getIcon('compare'); ?></a></li>
                        <?php endif; ?>
						  </ul>
					<?php } ?>
				</div>
            </div>
        </li>
    <?php if (++$i == $_collectionSize ) break; endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   onComplete: function(){
					jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
						jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
						jQuery.fancybox.resize();
					 });

				   }
				}
			);
			
			<?php if($moreviews): ?>
			/* ajax more views */
			ajaxMoreViews();
			<?php endif; ?>
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe,name){
			if(data.status == 'ERROR'){
				jQuery('body').append('<div class="add-to-cart-success">' + data.message+'<a href="#" class="btn-remove"><i class="fa fa-times" /></a></div>');
			}else{
				if(data.sidebar){
					if(jQuery('.top-cart')){
						jQuery('.top-cart').replaceWith(data.sidebar);
						if(jQuery('#cart-sidebar').length){
							jQuery('#cart-sidebar').html(jQuery(data.sidebar).find('#mini-cart'));
						}
					}
					jQuery.fancybox.close();
					jQuery('body').append('<div class="add-to-cart-success">' + data.message +' <br /><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('Go to Shopping Cart') ?></span></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
					
				}else{
					jQuery.ajax({
						url: "<?php echo $this->getUrl('meigeeactions/updatecart/') ?>",
						cache: false
					}).done(function(html){
						jQuery('header#header .top-cart').replaceWith(html);
						jQuery('.top-cart #mini-cart li.item a.btn-remove').on('click', function(event){
							event.preventDefault();
							jQuery('body').append('<div class="cart-remove-box"><?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?><br/><a href="'+ jQuery(this).attr('href') +'" class="confirm"><span><?php echo $this->__('Ok') ?></span></a><a href="#" class="cancel"><span><?php echo $this->__('Cancel') ?></span></a></div>');
							jQuery('.cart-remove-box a').on('click', function(){
								link = jQuery(this).attr('href');
								jQuery.ajax({
									url: link,
									cache: false
								});
								jQuery('.cart-remove-box').remove();
								setTimeout(function(){window.location.reload();}, 800);
							});
						});
					});
					jQuery.fancybox.close();
					jQuery('body').append('<div class="add-to-cart-success">' + name +' <?php echo $this->__('was added to your shopping cart.') ?> <br /><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('Go to Shopping Cart') ?></span></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
				}
			}
			setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);
			jQuery('.add-to-cart-success a.btn-remove').click(function(){
				jQuery(this).parent().slideUp(500);
				return false;
			});
		}
		function setLocationAjax(url,id,name){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax({
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						jQuery('.products-grid li.item').removeClass('active');
						setAjaxData(data,false,name);
					}
				});
			} catch (e) {
			}
		}
	</script>